"""fix(album): user_id -> tenant_id

Revision ID: 2d73800a7296
Revises: c8ac239fec19
Create Date: 2026-04-03 12:41:28.860236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d73800a7296'
down_revision: Union[str, Sequence[str], None] = 'c8ac239fec19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('album_user_id_fkey', 'album', type_='foreignkey')
    op.drop_column('album', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('album_user_id_fkey'), 'album', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
