"""major fix: change image to unscoped and remove tenant related in db operations

Revision ID: 4856c121aeeb
Revises: 2d73800a7296
Create Date: 2026-04-04 10:31:47.079475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4856c121aeeb'
down_revision: Union[str, Sequence[str], None] = '2d73800a7296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_album_slug'), table_name='album')
    op.create_index(op.f('ix_album_slug'), 'album', ['slug'], unique=False)
    op.create_unique_constraint('uq_album_tenant_slug', 'album', ['tenant_id', 'slug'])
    op.drop_index(op.f('ix_images_slug'), table_name='images')
    op.create_index(op.f('ix_images_slug'), 'images', ['slug'], unique=False)
    op.create_unique_constraint('uq_image_album_slug', 'images', ['album_id', 'slug'])
    op.drop_constraint(op.f('images_user_id_fkey'), 'images', type_='foreignkey')
    op.drop_column('images', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('images_user_id_fkey'), 'images', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_image_album_slug', 'images', type_='unique')
    op.drop_index(op.f('ix_images_slug'), table_name='images')
    op.create_index(op.f('ix_images_slug'), 'images', ['slug'], unique=True)
    op.drop_constraint('uq_album_tenant_slug', 'album', type_='unique')
    op.drop_index(op.f('ix_album_slug'), table_name='album')
    op.create_index(op.f('ix_album_slug'), 'album', ['slug'], unique=True)
    # ### end Alembic commands ###
