"""refactor: Change Gallery to Image and Album 

Revision ID: bc7a92d8585f
Revises: 44726cc8df9d
Create Date: 2026-01-26 18:03:34.581211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7a92d8585f'
down_revision: Union[str, Sequence[str], None] = '44726cc8df9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_slug'), 'album', ['slug'], unique=True)
    op.add_column('images', sa.Column('album_id', sa.UUID(), nullable=False))
    op.create_foreign_key('fk_images_album_id', 'images', 'album', ['album_id'], ['id'], ondelete='CASCADE')
    op.drop_column('images', 'is_published')
    op.drop_column('images', 'caption')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('caption', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('images', sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'album_id')
    op.drop_index(op.f('ix_album_slug'), table_name='album')
    op.drop_table('album')
    # ### end Alembic commands ###
