"""refactor(album): Made it tenantScope

Revision ID: c8ac239fec19
Revises: e99ddd4040a8
Create Date: 2026-03-22 04:57:50.822362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ac239fec19'
down_revision: Union[str, Sequence[str], None] = 'e99ddd4040a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'album', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'album', type_='foreignkey')
    op.drop_column('album', 'tenant_id')
    # ### end Alembic commands ###
