"""feat: added softdelete to event table 

Revision ID: d054e9250e86
Revises: bc7a92d8585f
Create Date: 2026-02-01 13:21:41.325904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd054e9250e86'
down_revision: Union[str, Sequence[str], None] = 'bc7a92d8585f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_events_deleted_at'), 'events', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_deleted_at'), table_name='events')
    op.drop_column('events', 'deleted_at')
    # ### end Alembic commands ###
